# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Assessment4' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Assessment4
pod 'ProgressHUD'

  target 'Assessment4Tests' do
    inherit! :search_paths
    # Pods for testing

  end

  target 'Assessment4UITests' do
    # Pods for testing
    
  end

end
